### ISSUE TITLE
Linkrot: http://itc.ktu.lt/itc353/Stage353.pdf

### ISSUE THREAD

**Issue by jdittrich** [jancborchardt/jancborchardt.net#2]
The linked document "Andreasen, M. S., Nielsen, H. V., Schrøder, S. O., Stage, J. (2006). Usability in Open Source Software Development: Opinions and Practice."  in *Usability in Free Software* is linkrotten: http://itc.ktu.lt/itc353/Stage353.pdf leads to no document.

**Comment by jancborchardt** [comment]
@jdittrich can you find a current valid link for the document? If you like, a pull request to fix it would be very welcome. :)

**Comment by jdittrich** [comment]
http://itc.ktu.lt/index.php/ITC/article/view/11776 should work.

**Comment by jancborchardt** [comment]
@jdittrich you want to fix that directly? :) Just click the edit-pencil on the top right of https://github.com/jancborchardt/jancborchardt.github.com/blob/master/usability-in-free-software.html and change the link. :) Good way to take first steps with Github editing.

**Comment by jancborchardt** [comment]
Fixed by https://github.com/jancborchardt/jancborchardt.github.com/pull/3 - thanks! :)
